### ISSUE TITLE
The server does not show the php file, it generates a file download php

### ISSUE THREAD

**Issue by cistelsa** [budisteikul/openshift-cartridge-nginx-php7#1]
Excellently shows the index.php file, but any php file loaded in the site root public /. generates the error and the page is not displayed but the .php file is downloaded. Please collaboration and excuse me my English language.

**Comment by budisteikul** [comment]
Currently the `.openshift/nginx.conf.erb` configuration template for nginx only redirects to the `public/index.php` file. You can change this by editing the template file.

**Example** 

```
# pass the PHP scripts to PHP-FPM 
location ~ ^/index\.php(/|$) {
```

replaced with

```
# pass the PHP scripts to PHP-FPM
location ~ \.php$ {
```

Also see http://wiki.nginx.org/Symfony for some extra information.

**Comment by cistelsa** [comment]
Thank you very much worked for me excellent.

I have another question, I can enter some kind of extension or library to enable connection to MSSQL database?, have a remote database Microsoft SQL Server 2005, which want to connect me to use just a few data, and the primary database will be mysql.

**Comment by budisteikul** [comment]
Yes! You can install and use any extension or library.
Just SSH to your application, enter to your source code directory, and run

```
phpize
./configure
make install
```

but, afaik in PHP 7 the MSSQL functions are removed (For example, mssql_connect) or not ported yet
https://wiki.php.net/rfc/removal_of_dead_sapis_and_exts
