### ISSUE TITLE
Problem with cartridge size

### ISSUE THREAD

**Issue by cistelsa** [budisteikul/openshift-cartridge-nginx-php7#4]
I really like this project, I have already put into production several websites, but I encounter a big problem, when decompressing the files this is very heavy over 200MB, apart MYSQL and PHPMYADMIN also bring in the hard drive, then for the application There is not much space available, I've seen another NGINX cartridge with PHP7 and decompressed it does not weigh more than 40MB. How do I solve this? I appreciate your response.

**Comment by budisteikul** [comment]
maybe you can remove file like `nginx-php/usr/bin/php-cgi` and `nginx-php/usr/bin/phpdbg` to save some storage
