### ISSUE TITLE
Access RHC Set Env Vars

### ISSUE THREAD

**Issue by ddxdental** [budisteikul/openshift-cartridge-nginx-php7#5]
Environment variables set via the rhc don't seem to be accessible to PHP via getenv.  What is the recommended way to set and access environmental vars?

**Comment by budisteikul** [comment]
after set env via rhc command, you must update file under `.openshift/php-fpm.ini.erb` change the line

`variables_order = "GPCS"`

to

`variables_order = "EGPCS"`

then add some line on file under `.openshift/php-fpm.conf.erb`

`env[My_Variable] = $My_Variable`

Ex.

> env[DB_DATABASE]  = $DB_DATABASE
> env[DB_HOST]  = $DB_HOST
> env[DB_PASSWORD]  = $DB_PASSWORD
> env[DB_USERNAME]  = $DB_USERNAME
