### ISSUE TITLE
Document the 'update force' function

### ISSUE THREAD

**Issue by colinwilson** [budisteikul/openshift-cartridge-nginx-php7#6]
Just ran

```
# update check
# update install
```

which failed (not sure why yet) to update PHP to the latest version (7.1.1 from 7.0.12).

When I ran `update check` & `update install` again I received:

```
# update check
Checking for updates...
Your cartridge version is 5.3.0 and already up to date.

# update install
No updates available.
Please run `update check` to check for updates
```
Didn't realise there was an `update force` function till I checked the [update script](https://github.com/budisteikul/openshift-cartridge-nginx-php7/blob/master/usr/bin/update#L74) looking for a way to do just this.

Maybe document this function in the README?

**Comment by budisteikul** [comment]
okay thank you, i will add this in README later.
