### ISSUE TITLE
how to integrate with cartridge phpMyAdmin and MySQL?

### ISSUE THREAD

**Issue by erlangparasu** [budisteikul/openshift-cartridge-nginx-php7#9]
how to integrate with cartridge phpMyAdmin and MySQL? Thanks

**Comment by aneek** [comment]
Assumed that your application name is 'testme'. Then (via command line):

- Add MySQL: `rhc cartridge add -a testme mysql-5.5`
- Add phpMyAdmin: `rhc cartridge add -a testme phpmyadmin-4`

From UI, you will have step by step options.

Regards,
Aneek

**Comment by erlangparasu** [comment]
Thanks 👍
